#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Justin Hoyt"
email = "justinhoyt@google.com"

[ui]
editor = "nvim"
pager = "delta"
diff-formatter = ":git"

[git]
auto-local-bookmark = true

[aliases]
s = ["status"]
l = ["log"]
d = ["diff"]
desc = ["describe"]
sh = ["show"]
res = ["resolve"]
sp = ["split"]
sq = ["squash"]

# Parent (@-) explicit shortcuts:
dp = ["diff", "-r", "@-"]
descp = ["describe", "-r", "@-"]
shp = ["show", "-r", "@-"]
resp = ["resolve", "-r", "@-"]
spp = ["split", "-r", "@-"]
sqp = ["squash", "-r", "@-"]
