#!/usr/bin/env bash

FISH_VERSION="fish-3.7.1"

git submodule update --init --recursive

if test ! -d ${FISH_VERSION}; then tar -xf ${FISH_VERSION}.tar.xz; fi
if test ! -f ~/.zshrc_local; then touch ~/.zshrc_local; fi
if test ! -f ~/.bashrc_local; then touch ~/.bashrc_local; fi
if test ! -f ~/.tmux.local.conf; then touch ~/.tmux.local.conf; fi
if test ! -f ~/.config/fish/config.local.fish; then touch ~/.config/fish/config.local.fish; fi
if test ! -f ~/.config/nvim/lua/init_local.lua; then touch ~/.config/nvim/lua/init_local.lua; fi
if test ! -f proxy_url; then touch proxy_url; echo "proxy_url=" > proxy_url; fi
if test ! -f ~/.gitignore; then git config --global core.excludesFile ~/.gitignore; fi
if test ! -f ~/.tmux/plugins/tpm; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh
fi

./install
